version: "3.9"
services:
  ds_front:
    build:
      context: ./ds-front
      args:
        SERVER_ADDRESS: http://${SERVER_HOST}:${SERVER_PORT}
    container_name: ds-front_${FRONT_PORT}
    working_dir: /ds-front
    ports:
      - "${FRONT_PORT}:8080"
    command: serve -s dist -l 8080
    restart: unless-stopped

  ds_back:
    build: ./ds-back
    container_name: ds-back_${SERVER_PORT}
    working_dir: /ds-back
    ports:
      - "${SERVER_PORT}:3000"
    environment:
      MONGODB_CONNSTRING: mongodb://${DB_USER}:${DB_PWD}@mongodb
    command: node dist/main
    restart: unless-stopped
    links:
      - mongodb

  mongodb:
    image: mongo:5.0
    container_name: ds-mongo_${DB_PORT}
    environment:
      DB_USER: ${DB_USER}
      DB_PWD: ${DB_PWD}
      DB_NAME: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PWD}
    ports:
      - "${DB_PORT}:27017"
    volumes:
      - ./data:/data/db
      - ./init-mongodb:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped